# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NurseSchedule_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FSCalendar'
pod 'RealmSwift'
pod 'CSV.swift', '~> 2.4.3'
pod 'SwiftCSV'
  # Pods for NurseSchedule_iOS
pod 'FSPagerView'
end
